name: update website
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.2
      - run: pnpm install --prefer-offline

      - name: Build
        run: pnpm run docs:build

      - name: Deploy to Pages
        run: |
          cd docs/.vitepress/dist
          git config --global init.defaultBranch master
          git init
          git config user.email "${{secrets.EMAIL}}"
          git config user.name "${{github.repository_owner}}"
          git add -A
          git commit -m 'deploy'
          git push -f https://${{github.repository_owner}}:${{ secrets.TOKEN }}@github.com/${{github.repository}}.git master:gh-pages
